"""creating revoked_at,replaced_by  columns in Refresh Tokens Table- First Migartion

Revision ID: 706f8bdff625
Revises: ba79b4dab4ff
Create Date: 2026-09-10 21:24:09.740146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '706f8bdff625'
down_revision: Union[str, Sequence[str], None] = 'ba79b4dab4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_hash', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_refresh_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_column('refresh_tokens', 'revoked')
    op.drop_column('refresh_tokens', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('refresh_token', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('refresh_tokens', sa.Column('revoked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_refresh_token'), 'refresh_tokens', ['refresh_token'], unique=True)
    op.drop_column('refresh_tokens', 'token_hash')
    # ### end Alembic commands ###
