"""creating Refresh Token  table - Second Migartion

Revision ID: 9a7201a6d373
Revises: 5ce9e0beb91b
Create Date: 2026-09-10 16:20:08.458700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a7201a6d373'
down_revision: Union[str, Sequence[str], None] = '5ce9e0beb91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'refresh_token',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'refresh_token',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
