"""creating revoked_at,replaced_by  columns in Refresh Tokens Table- First Migartion

Revision ID: ba79b4dab4ff
Revises: fbcbb9737466
Create Date: 2026-09-10 21:19:03.350146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba79b4dab4ff'
down_revision: Union[str, Sequence[str], None] = 'fbcbb9737466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('replaced_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'refresh_tokens', 'refresh_tokens', ['replaced_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_column('refresh_tokens', 'replaced_by')
    op.drop_column('refresh_tokens', 'revoked_at')
    # ### end Alembic commands ###
